
name: 'ra_dw_framework'
version: '0.0.1'
require-dbt-version: ">=0.17.0"
config-version: 2

profile: ra_dw_framework

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

on-run-start:
    - "create table if not exists {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object string, status string, row_count numeric, execution_time numeric, load_ts timestamp)"

on-run-end:
    - "insert into {{ generate_prefixed_target_name() }}_logs.audit_dbt_results (object, status, row_count, execution_time, load_ts) values {{ results_values(results) }}"

models:
    ra_dw_framework:
        staging:
            materialized: view
            schema: staging
        integration:
            materialized: view
            schema: integration
        warehouse:
            materialized: table
        utils:
            materialized: table
            schema: logs
            enabled: false